# Generated by rust2rpm 10
%bcond_without check
%global debug_package %{nil}

%global crate byte-unit

Name:           rust-%{crate}
Version:        3.0.3
Release:        2%{?dist}
Summary:        Library for interaction with units of bytes

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/byte-unit
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Library for interaction with units of bytes.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 3.0.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Sep 16 11:06:41 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 3.0.3-1
- Update to 3.0.3

* Sun Sep 08 18:06:58 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 3.0.1-1
- Initial package
